### ISSUE TITLE
gfortran 8.3.1 fails parameter_list_type test

### ISSUE THREAD

**Issue by nncarlson** [nncarlson/petaca#15]
I'm testing the current version of gcc 8 (8.3.1-20190406) and test_parameter_list_type is throwing this runtime error:
```
$ ./test_parameter_list_type 
At line 768 of file /opt/src/petaca/petaca/src/parameter_entry_class.F90
Fortran runtime error: Array bound mismatch for dimension 1 of array '<<unknown>>' (4/2)

Error termination. Backtrace:
#0  0x7fd646cbaf9a in ???
#1  0x7fd646cbbb85 in ???
#2  0x7fd646cbbf57 in ???
#3  0x41ba84 in __parameter_entry_class_MOD___copy_parameter_entry_class_Any_matrix
	at /opt/src/petaca/petaca/src/parameter_entry_class.F90:768
#4  0x4199ad in new_list_item
	at /opt/src/petaca/petaca/src/map_any_type.F90:166
#5  0x419236 in __map_any_type_MOD_insert
	at /opt/src/petaca/petaca/src/map_any_type.F90:249
#6  0x43d206 in __parameter_list_type_MOD_set_matrix
	at /opt/src/petaca/petaca/src/parameter_list_type.F90:638
#7  0x416acd in test_basic
	at /opt/src/petaca/petaca/test/parameter_list_type/test_parameter_list_type.F90:69
#8  0x400e46 in test_parameter_list_type
	at /opt/src/petaca/petaca/test/parameter_list_type/test_parameter_list_type.F90:32
#9  0x417432 in main
	at /opt/src/petaca/petaca/test/parameter_list_type/test_parameter_list_type.F90:27
```
I haven't investigated further. I suspect a compiler bug, and this may be the same thing as #14.

**Comment by nncarlson** [comment]
This is with "-fcheck=all -Wall -Wextra", which cmake uses for the Debug build type. No error with Release build type.

**Comment by nncarlson** [comment]
Same problem with gfortran 9.1

**Comment by nncarlson** [comment]
All tests are passing now with gfortran 9.x and 10.x.  Though see #24.
